language: c

sudo: false

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libcunit1 libcunit1-doc libcunit1-dev

addons:
  apt:
    packages:
      - libcunit1
      - libcunit-dev

script: make && make runtests
